id = "jetbrains-themes"
name = "JetBrains Themes"
version = "0.2.0"
schema_version = 1
authors = ["Artem Evsevev <artem@qrsoft.ru>"]
description = "Light and Dark JetBrains themes"
repository = "https://github.com/artemevsevev/zed-theme-jetbrains"
