id = "jetbrains-themes"
name = "JetBrains Themes"
version = "1.0.0"
schema_version = 1
authors = ["Artem Evsevev <artem@qrsoft.ru>"]
description = "Light, Dark, Islands Light and Islands Dark JetBrains themes"
repository = "https://github.com/artemevsevev/zed-theme-jetbrains"
